#!/bin/bash

python3 -m pip install --no-build-isolation -e .

which starsmashertools &>/dev/null
if [ $? -ne 0 ]; then
    echo "Warning: cannot find command 'starsmashertools'"
    echo "To complete your installation add the following line to $HOME/.bashrc:"
    echo '   export PATH="$HOME/.local/bin:$PATH"'
    echo "Then refresh your environment:"
    echo '   source ~/.bashrc'
fi
