#!/usr/bin/env python3

# This requires a tool called "Guppy 3"
# https://github.com/zhuyifei1999/guppy3?tab=readme-ov-file
# https://smira.ru/wp-content/uploads/2011/08/heapy.html

from guppy import hpy
import os

hp = hpy()


import starsmashertools
import starsmashertools.lib.flux

previous_size = None

for i in range(10):
    hp.setrelheap()
    simulation = starsmashertools.get_simulation('check_leaks_simulation')
    output = simulation.get_output()
    finder = starsmashertools.lib.flux.FluxFinder(output)
    finder.get()
    finder.result.save()
    h = hp.heap()
    if os.path.isfile('flux.zip'): os.remove('flux.zip')
    print("Heap size =",h.size)
    if previous_size is not None:
        if h.size > previous_size:
            raise MemoryError("Heap size increased by %d from %d to %d\n%s" % ((h.size - previous_size), previous_size, h.size, h))
    previous_size = h.size
    



