#!/usr/bin/env python3

if __name__ == '__main__':
    import zipfile
    import os
    import shutil
    
    code = ''
    listening = False
    with open('extract', 'r') as f:
        for line in f:
            if line.startswith('# Start restore code'):
                listening = True
                continue
            if listening:
                if line.startswith('# Stop restore code'):
                    break
                code += line

    exec(code)

    code = get_compress_code()
    for script in code.values():
        exec(script)

    filenames = []
    with zipfile.ZipFile(
            zipname,
            mode = 'r',
            **compression_kwargs,
    ) as zfile:
        for zinfo in zfile.infolist():
            if zinfo.filename in [size_identifier, times_identifier]: continue
            filenames += [zinfo.filename]

    directories = []
    for filename in filenames:
        dirname = os.path.dirname(filename)
        while os.sep in dirname:
            dirname = os.path.dirname(dirname)
        if dirname not in directories:
            directories += [dirname]

    for directory in directories:
        if os.path.isdir(directory): shutil.rmtree(directory)
        elif os.path.isfile(directory): os.remove(directory)
    
