#!/usr/bin/env python3

def restore():
    import shutil
    import os
    import zipfile
    from importlib.util import spec_from_loader, module_from_spec
    from importlib.machinery import SourceFileLoader 

    spec = spec_from_loader('compress', SourceFileLoader('compress', 'compress'))
    compress = module_from_spec(spec)
    spec.loader.exec_module(compress)
    
    if not os.path.isfile(compress.zipname): quit()
        
    filenames = []
    with zipfile.ZipFile(
            compress.zipname,
            mode = 'r',
            **compress.compression_kwargs,
    ) as zfile:
        for zinfo in zfile.infolist():
            if zinfo.filename in [
                    compress.size_identifier,
                    compress.times_identifier
            ]: continue
            filenames += [zinfo.filename]

    directories = []
    for filename in filenames:
        dirname = os.path.dirname(filename)
        while os.sep in dirname:
            dirname = os.path.dirname(dirname)
        if dirname in directories: continue
        directories += [dirname]
    
    for directory in directories:
        if os.path.isdir(directory): shutil.rmtree(directory)
        elif os.path.isfile(directory): os.remove(directory)
    

if __name__ == '__main__': restore()
