#!/usr/bin/env python3

import subprocess
import starsmashertools
import os
import sys

os.chdir(os.path.join(
    starsmashertools.SOURCE_DIRECTORY,
    'dev',
))

try:
    p = subprocess.run(
        ['python3', 'increment_version', '-y'],
        check = True,
        text = True,
        stdout = subprocess.PIPE,
        stderr = subprocess.STDOUT,
    )
except subprocess.CalledProcessError as e:
    print(e.returncode)
    print(e.output)
    sys.exit(1)

if p.stdout and 'Traceback' in p.stdout:
    print(p.stdout)
    sys.exit(1)
