#!/usr/bin/env python3

import subprocess
import starsmashertools
import os
import sys

os.chdir(os.path.join(
    starsmashertools.SOURCE_DIRECTORY,
    'dev',
))

try:
    p = subprocess.run(
        ['python3', 'increment_version', '-y'],
        check = True,
        text = True,
        stdout = subprocess.PIPE,
        stderr = subprocess.STDOUT,
    )
    if p.stdout and 'Traceback' in p.stdout:
        print(p.stdout)
        sys.exit(1)
except subprocess.CalledProcessError as e:
    print(e.returncode)
    print(e.output)
    sys.exit(1)



# Add our changes to the current commit
os.chdir(starsmashertools.SOURCE_DIRECTORY)
try:
    p = subprocess.run(
        ['git', 'add', 'pyproject.toml', 'dev/version_data.json.zip'],
        check = True,
        text = True,
        stdout = subprocess.PIPE,
        stderr = subprocess.STDOUT,
    )
    if p.stdout and 'Traceback' in p.stdout:
        print(p.stdout)
        sys.exit(1)
except subprocess.CalledProcessError as e:
    print(e.returncode)
    print(e.output)
    sys.exit(1)

sys.exit(0)
