#!/usr/bin/env python3

import subprocess
import starsmashertools
import os
import sys

test_dir = os.path.join(
    starsmashertools.SOURCE_DIRECTORY,
    'tests',
)

curdir = os.getcwd()
os.chdir(test_dir)
p = subprocess.run(
    ['python3', 'run_all_tests.py'],
    check = True,
    capture_output = True,
    text = True,
)
if 'FAILED' in p.stderr:
    print(p.stderr)
    sys.exit(1)

os.chdir(os.path.join(
    starsmashertools.SOURCE_DIRECTORY,
    'dev',
))
p = subprocess.run(
    ['increment_version'],
    check = True,
    capture_output = True,
    text = True,
)
if 'Traceback' in p.stderr:
    print(p.stderr)
    sys.exit(1)
    
sys.exit(0)

